"""add indexes for earnings performance

Revision ID: 0e7e80773215
Revises: c2e0f0c03e6c
Create Date: 2025-12-02 15:31:51.391643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e7e80773215'
down_revision: Union[str, Sequence[str], None] = 'c2e0f0c03e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, set NULL paid_at values to created_at (or current timestamp) before making it NOT NULL
    op.execute("""
        UPDATE commissions 
        SET paid_at = COALESCE(created_at, NOW()) 
        WHERE paid_at IS NULL
    """)
    
    op.alter_column('commissions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('commissions', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referrals', 'referred_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Create indexes only if they don't exist
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('referrals')}
    existing_user_indexes = {idx['name'] for idx in inspector.get_indexes('users')}
    
    if 'idx_referrals_created_at' not in existing_indexes:
        op.create_index('idx_referrals_created_at', 'referrals', ['created_at'], unique=False)
    if 'idx_referrals_referrer_created' not in existing_indexes:
        op.create_index('idx_referrals_referrer_created', 'referrals', ['referrer_id', 'created_at'], unique=False)
    if 'idx_referrals_referrer_id' not in existing_indexes:
        op.create_index('idx_referrals_referrer_id', 'referrals', ['referrer_id'], unique=False)
    if 'idx_users_subscription_status' not in existing_user_indexes:
        op.create_index('idx_users_subscription_status', 'users', ['subscription_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_subscription_status', table_name='users')
    op.drop_index('idx_referrals_referrer_id', table_name='referrals')
    op.drop_index('idx_referrals_referrer_created', table_name='referrals')
    op.drop_index('idx_referrals_created_at', table_name='referrals')
    op.alter_column('referrals', 'referred_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('commissions', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('commissions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
