"""Update user chops columns

Revision ID: 190e2f51f216
Revises: 73bb7846f6eb
Create Date: 2025-11-26 05:51:03.002730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190e2f51f216'
down_revision: Union[str, Sequence[str], None] = '73bb7846f6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_analyses', 'ai_tools_data')
    op.drop_column('business_analyses', 'roi_projections')
    op.add_column('insights', sa.Column('total_views', sa.Integer(), nullable=True))
    op.add_column('insights', sa.Column('total_shares', sa.Integer(), nullable=True))
    op.alter_column('insights', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('insights', 'image')
    op.add_column('users', sa.Column('alert_reading_chops', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('alert_sharing_chops', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('insight_reading_chops', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('insight_sharing_chops', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_column('users', 'reading_chops')
    op.drop_column('users', 'sharing_chops')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sharing_chops', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reading_chops', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'insight_sharing_chops')
    op.drop_column('users', 'insight_reading_chops')
    op.drop_column('users', 'alert_sharing_chops')
    op.drop_column('users', 'alert_reading_chops')
    op.add_column('insights', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('insights', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('insights', 'total_shares')
    op.drop_column('insights', 'total_views')
    op.add_column('business_analyses', sa.Column('roi_projections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('ai_tools_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
