"""Add subscription status and plan to users table

Revision ID: 30819a16afaa
Revises: 2b19243fb3e1
Create Date: 2025-11-18 13:38:06.813868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30819a16afaa'
down_revision: Union[str, Sequence[str], None] = '2b19243fb3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('tx_ref', sa.String(), nullable=False))
    op.create_index(op.f('ix_subscriptions_tx_ref'), 'subscriptions', ['tx_ref'], unique=True)
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'subscription_status')
    op.drop_index(op.f('ix_subscriptions_tx_ref'), table_name='subscriptions')
    op.drop_column('subscriptions', 'tx_ref')
    # ### end Alembic commands ###
