"""Add changes made to existing database tables

Revision ID: 6b941bae0ca9
Revises: 0e7e80773215
Create Date: 2025-12-03 12:58:56.908228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b941bae0ca9'
down_revision: Union[str, Sequence[str], None] = '0e7e80773215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check existing columns to avoid duplicate errors
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = {col['name'] for col in inspector.get_columns('commissions')}
    
    # Add columns only if they don't exist
    if 'referred_user_id' not in existing_columns:
        op.add_column('commissions', sa.Column('referred_user_id', sa.Integer(), nullable=True))
    if 'subscription_id' not in existing_columns:
        op.add_column('commissions', sa.Column('subscription_id', sa.Integer(), nullable=True))
    if 'original_amount' not in existing_columns:
        op.add_column('commissions', sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    if 'currency' not in existing_columns:
        op.add_column('commissions', sa.Column('currency', sa.String(length=10), nullable=True))
    if 'commission_rate' not in existing_columns:
        op.add_column('commissions', sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    if 'created_at' not in existing_columns:
        op.add_column('commissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    if 'approved_at' not in existing_columns:
        op.add_column('commissions', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    if 'payout_id' not in existing_columns:
        op.add_column('commissions', sa.Column('payout_id', sa.Integer(), nullable=True))
    
    op.alter_column('commissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commissions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('commissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('commissions', 'paid_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    
    # Add indexes only if they don't exist
    existing_indexes = {idx['name'] for idx in inspector.get_indexes('commissions')}
    if 'idx_commissions_created_at' not in existing_indexes:
        op.create_index('idx_commissions_created_at', 'commissions', ['created_at'], unique=False)
    if 'idx_commissions_user_status' not in existing_indexes:
        op.create_index('idx_commissions_user_status', 'commissions', ['user_id', 'status'], unique=False)
    
    # Foreign keys - these need special handling
    try:
        op.create_foreign_key('fk_commissions_payout', 'commissions', 'payouts', ['payout_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key('fk_commissions_referred_user', 'commissions', 'users', ['referred_user_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key('fk_commissions_subscription', 'commissions', 'subscriptions', ['subscription_id'], ['id'])
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.drop_index('idx_commissions_user_status', table_name='commissions')
    op.drop_index('idx_commissions_created_at', table_name='commissions')
    op.alter_column('commissions', 'paid_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('commissions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('commissions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('commissions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('commissions', 'payout_id')
    op.drop_column('commissions', 'approved_at')
    op.drop_column('commissions', 'created_at')
    op.drop_column('commissions', 'commission_rate')
    op.drop_column('commissions', 'currency')
    op.drop_column('commissions', 'original_amount')
    op.drop_column('commissions', 'subscription_id')
    op.drop_column('commissions', 'referred_user_id')
    # ### end Alembic commands ###
