"""Make commissions table payout_id  nullable

Revision ID: a791f64341b2
Revises: 85421d151c43
Create Date: 2025-12-03 17:06:40.583056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a791f64341b2'
down_revision: Union[str, Sequence[str], None] = '85421d151c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commissions', 'payout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commissions', 'payout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
