"""Add the changes made to various tables in our database

Revision ID: cd505f22437a
Revises: 775f7104fa44
Create Date: 2025-12-15 00:14:41.010270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd505f22437a'
down_revision: Union[str, Sequence[str], None] = '775f7104fa44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_column('alerts', 'url')
    op.drop_column('business_analyses', 'insights_count')
    op.drop_column('business_analyses', 'analysis_type')
    op.drop_column('business_analyses', 'duration')
    op.drop_column('business_analyses', 'recommendations_count')
    op.drop_column('business_analyses', 'confidence_score')
    op.drop_column('insights', 'url')
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'user_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'two_factor_enabled')
    op.add_column('insights', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('recommendations_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('analysis_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('insights_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_table('trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engagement', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('growth', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('viral_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_volume', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('peak_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('competition', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('opportunity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('trends_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trends_pkey'))
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    # ### end Alembic commands ###
