"""Create subscriptions table and add all columns

Revision ID: f76ba9dc56d7
Revises: 0cc5cde92836
Create Date: 2025-11-19 14:03:49.079768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76ba9dc56d7'
down_revision: Union[str, Sequence[str], None] = '0cc5cde92836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
