"""Add the appropriate columns to the security tables

Revision ID: fbd856f8ccd8
Revises: b2f621d9eb29
Create Date: 2025-12-22 15:48:19.047551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbd856f8ccd8'
down_revision: Union[str, Sequence[str], None] = 'b2f621d9eb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_metrics_summary',
    sa.Column('total_events_24h', sa.Integer(), nullable=False),
    sa.Column('high_severity_events_24h', sa.Integer(), nullable=True),
    sa.Column('blocked_attacks_24h', sa.Integer(), nullable=True),
    sa.Column('failed_logins_24h', sa.Integer(), nullable=True),
    sa.Column('active_blacklisted_ips', sa.Integer(), nullable=True),
    sa.Column('active_firewall_rules', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('total_events_24h')
    )
    op.drop_index(op.f('ix_trends_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('idx_alerts_url'), table_name='alerts')
    op.drop_index(op.f('idx_business_analyses_analysis_type'), table_name='business_analyses')
    op.drop_index(op.f('idx_business_analyses_created_at'), table_name='business_analyses')
    op.drop_index(op.f('idx_business_analyses_status'), table_name='business_analyses')
    op.drop_column('business_analyses', 'analysis_type')
    op.drop_column('business_analyses', 'duration')
    op.drop_column('business_analyses', 'insights_count')
    op.drop_column('business_analyses', 'confidence_score')
    op.drop_column('business_analyses', 'recommendations_count')
    op.drop_index(op.f('idx_insights_url'), table_name='insights')
    op.drop_index(op.f('idx_service_health_created'), table_name='service_health')
    op.create_index('idx_service_health_created', 'service_health', ['created_at'], unique=False)
    op.add_column('system_metrics', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_system_metrics_created_at', 'system_metrics', ['created_at'], unique=False)
    op.create_index('idx_system_metrics_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.alter_column('users', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_last_login'), table_name='users')
    op.drop_index(op.f('idx_users_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_status'), 'users', ['user_status'], unique=False)
    op.create_index(op.f('idx_users_last_login'), 'users', ['last_login'], unique=False)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'user_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('idx_system_metrics_timestamp', table_name='system_metrics')
    op.drop_index('idx_system_metrics_created_at', table_name='system_metrics')
    op.drop_column('system_metrics', 'updated_at')
    op.drop_index('idx_service_health_created', table_name='service_health')
    op.create_index(op.f('idx_service_health_created'), 'service_health', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_insights_url'), 'insights', ['url'], unique=False)
    op.add_column('business_analyses', sa.Column('recommendations_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('insights_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('analysis_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_business_analyses_status'), 'business_analyses', ['status'], unique=False)
    op.create_index(op.f('idx_business_analyses_created_at'), 'business_analyses', ['created_at'], unique=False)
    op.create_index(op.f('idx_business_analyses_analysis_type'), 'business_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('idx_alerts_url'), 'alerts', ['url'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('engagement', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('growth', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('viral_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('search_volume', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('peak_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('competition', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('opportunity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('action_items', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('trends_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('trends_pkey'))
    )
    op.create_index(op.f('ix_trends_id'), 'trends', ['id'], unique=False)
    op.drop_table('security_metrics_summary')
    # ### end Alembic commands ###
