"""add user_pinned_alerts table

Revision ID: 99a3cffb50d4
Revises: 190e2f51f216
Create Date: 2025-11-28 03:48:01.561547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a3cffb50d4'
down_revision: Union[str, Sequence[str], None] = '190e2f51f216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_analyses', 'roi_projections')
    op.drop_column('business_analyses', 'ai_tools_data')
    op.add_column('user_pinned_alerts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('user_pinned_alerts', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.add_column('user_pinned_alerts', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user_pinned_alerts', 'alerts', ['alert_id'], ['id'])
    op.create_foreign_key(None, 'user_pinned_alerts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_pinned_alerts', type_='foreignkey')
    op.drop_constraint(None, 'user_pinned_alerts', type_='foreignkey')
    op.drop_column('user_pinned_alerts', 'pinned_at')
    op.drop_column('user_pinned_alerts', 'alert_id')
    op.drop_column('user_pinned_alerts', 'user_id')
    op.add_column('business_analyses', sa.Column('ai_tools_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('business_analyses', sa.Column('roi_projections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
